using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SonicPoints.Data;
using SonicPoints.Models;
using SonicPoints.Dto;
using System.Security.Claims;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using QuestPDF.Drawing;
using System.Text;

namespace SonicPoints.Controllers
{
    [Route("api/reports")]
    [ApiController]
    [Authorize]
    public class ReportController : ControllerBase
    {
        private readonly AppDbContext _context;

        public ReportController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet("project/{projectId}/download-all-reports")]
        [Authorize(Roles = "Admin,Manager,SuperAdmin,Member")]
        public async Task<IActionResult> DownloadAllReportsAsPdf(int projectId)
        {
            var project = await _context.Projects.FindAsync(projectId);
            if (project == null) return NotFound("Project not found");

            var users = await _context.ProjectUsers
                .Where(pu => pu.ProjectId == projectId)
                .Include(pu => pu.User)
                .ToListAsync();

            var tasks = await _context.Tasks
                .Where(t => t.ProjectId == projectId)
                .ToListAsync();

            var redemptions = await _context.RedeemHistory
                .Where(r => r.ProjectId == projectId)
                .ToListAsync();

            var stream = new MemoryStream();

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);
                    page.Size(PageSizes.A4);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Header().Text($"📄 Project Report: {project.Name}")
                        .SemiBold().FontSize(18).FontColor(Colors.Blue.Darken2);

                    page.Content().Column(col =>
                    {
                        col.Spacing(15);
                        col.Item().Text($"🕒 Generated At: {DateTime.Now}");
                        col.Item().Text($"👥 Total Users: {users.Count}");

                        foreach (var pu in users)
                        {
                            var userTasks = tasks.Where(t => t.UserId == pu.UserId).ToList();

                            var countBacklog = userTasks.Count(t => t.Status == ProjectTaskStatus.Backlog);
                            var countInProgress = userTasks.Count(t => t.Status == ProjectTaskStatus.InProgress);
                            var countReview = userTasks.Count(t => t.Status == ProjectTaskStatus.Review);
                            var countCompleted = userTasks.Count(t => t.Status == ProjectTaskStatus.Completed);

                            var rewardCount = redemptions.Count(r => r.UserId == pu.UserId);
                            var username = pu.User?.UserName ?? "Unknown";

                            col.Item().Text($"- {username} (ID: {pu.UserId})").Bold();

                            col.Item().Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    columns.ConstantColumn(100);
                                    columns.ConstantColumn(80);
                                });

                                table.Header(header =>
                                {
                                    header.Cell().Text("Status").Bold();
                                    header.Cell().Text("Count").Bold();
                                });

                                table.Cell().Text("Backlog");
                                table.Cell().Text(countBacklog.ToString());
                                table.Cell().Text("InProgress");
                                table.Cell().Text(countInProgress.ToString());
                                table.Cell().Text("Review");
                                table.Cell().Text(countReview.ToString());
                                table.Cell().Text("Completed");
                                table.Cell().Text(countCompleted.ToString());
                            });

                            col.Item().Text($"🎁 Rewards Redeemed: {rewardCount}");
                            col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                        }
                    });

                    page.Footer().AlignCenter().Text("Generated by SonicPoints System");
                });
            }).GeneratePdf(stream);

            stream.Position = 0;
            return File(stream, "application/pdf", $"project_{projectId}_report.pdf");
        }

        [HttpPost("generate")]
        public async Task<IActionResult> GenerateReport()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (string.IsNullOrEmpty(userId))
                return Unauthorized("User not authenticated.");

            var tasksCompleted = await _context.Tasks
                .CountAsync(t => t.UserId == userId && t.Status == ProjectTaskStatus.Completed);

            var totalPoints = await _context.Leaderboards
                .Where(l => l.UserId == userId)
                .SumAsync(l => (int?)l.PointsEarned) ?? 0;

            var rewards = await _context.RedeemHistory
                .CountAsync(r => r.UserId == userId);

            var username = await _context.Users
                .Where(u => u.Id == userId)
                .Select(u => u.UserName)
                .FirstOrDefaultAsync() ?? "Unknown";

            var content = $"User Report for {username}\n" +
                          $"- Tasks Completed: {tasksCompleted}\n" +
                          $"- Total Points Earned: {totalPoints}\n" +
                          $"- Rewards Redeemed: {rewards}\n" +
                          $"- Report Generated At: {DateTime.UtcNow}";

            var report = new Report
            {
                UserId = userId,
                ReportContent = content,
                GeneratedAt = DateTime.UtcNow
            };

            _context.Reports.Add(report);
            await _context.SaveChangesAsync();

            return Ok(new ReportDto
            {
                ReportId = report.ReportId,
                UserId = int.TryParse(userId, out var uid) ? uid : 0,
                ReportContent = report.ReportContent,
                GeneratedAt = report.GeneratedAt,
                User = username
            });
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> GetAllReports()
        {
            var reports = await _context.Reports
                .OrderByDescending(r => r.GeneratedAt)
                .ToListAsync();
            return Ok(reports);
        }

        [HttpPost("project/{projectId}")]
        public async Task<IActionResult> GenerateProjectReport(int projectId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var project = await _context.Projects.FindAsync(projectId);
            if (project == null)
                return NotFound("Project not found.");

            var users = await _context.ProjectUsers
                .Where(pu => pu.ProjectId == projectId)
                .Include(pu => pu.User)
                .ToListAsync();

            if (!users.Any())
                return NotFound("No users found in this project.");

            var reportLines = new List<string>
            {
                $"Project Report for '{project.Name}'",
                $"Generated At: {DateTime.UtcNow}",
                $"Total Users: {users.Count}",
                $"-------------------------------------------------------------"
            };

            foreach (var pu in users)
            {
                var uid = pu.UserId;
                var userName = pu.User?.UserName ?? "Unknown";

                var tasks = await _context.Tasks
                    .Where(t => t.ProjectId == projectId && t.UserId == uid)
                    .ToListAsync();

                var countBacklog = tasks.Count(t => t.Status == ProjectTaskStatus.Backlog);
                var countInProgress = tasks.Count(t => t.Status == ProjectTaskStatus.InProgress);
                var countReview = tasks.Count(t => t.Status == ProjectTaskStatus.Review);
                var countCompleted = tasks.Count(t => t.Status == ProjectTaskStatus.Completed);
                var totalTasks = tasks.Count;

                var rewardCount = await _context.RedeemHistory
                    .CountAsync(r => r.ProjectId == projectId && r.UserId == uid);

                reportLines.Add(
                    $" {userName} (ID: {uid})\n" +
                    $"- Tasks: Backlog={countBacklog}, InProgress={countInProgress}, Review={countReview}, Completed={countCompleted}\n" +
                    $"- Total Tasks: {totalTasks}\n" +
                    $"- Rewards Redeemed: {rewardCount}\n"
                );
            }

            var reportText = string.Join("\n", reportLines);

            var report = new Report
            {
                UserId = userId,
                ReportContent = reportText,
                GeneratedAt = DateTime.UtcNow
            };

            _context.Reports.Add(report);
            await _context.SaveChangesAsync();

            return Ok(new
            {
                projectId,
                projectName = project.Name,
                generatedBy = userId,
                reportId = report.ReportId,
                report = reportText
            });
        }

      
        private byte[] GenerateStructuredPdf(string projectName, List<(string Username, int TasksCompleted, int Points, int Rewards)> data)
        {
            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);
                    page.Size(PageSizes.A4);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Header().Column(col =>
                    {
                        col.Item().Text("SonicPoints Project Report").Bold().FontSize(20);
                        col.Item().Text($"Project: {projectName}");
                        col.Item().Text($"Generated at: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}");
                    });

                    page.Content().Element(container =>
                    {
                        container.PaddingVertical(10).PaddingHorizontal(5).Stack(stack =>
                        {
                            stack.Item().Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    columns.RelativeColumn(3);
                                    columns.RelativeColumn(2);
                                    columns.RelativeColumn(2);
                                    columns.RelativeColumn(2);
                                });

                                table.Header(header =>
                                {
                                    header.Cell().Element(CellStyle).Text("Username").Bold();
                                    header.Cell().Element(CellStyle).Text("Tasks Completed").Bold();
                                    header.Cell().Element(CellStyle).Text("Points Earned").Bold();
                                    header.Cell().Element(CellStyle).Text("Rewards Redeemed").Bold();
                                });

                                foreach (var (username, tasksCompleted, points, rewards) in data)
                                {
                                    table.Cell().Element(CellStyle).Text(username ?? "Unknown");
                                    table.Cell().Element(CellStyle).Text(tasksCompleted.ToString());
                                    table.Cell().Element(CellStyle).Text(points.ToString());
                                    table.Cell().Element(CellStyle).Text(rewards.ToString());
                                }

                                static IContainer CellStyle(IContainer container)
                                {
                                    return container.PaddingVertical(4).PaddingHorizontal(3);
                                }
                            });
                        });
                    });

                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by SonicPoints • Page ");
                        x.CurrentPageNumber();
                        x.Span(" of ");
                        x.TotalPages();
                    });
                });
            }).GeneratePdf();
        }
    }
}
